require('dotenv').config({ path: './.env' });
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const connectDB = require('./db');
const User = require('../models/User');
const Product = require('../models/Product');
const Ad = require('../models/Ad');

const products = [
  { name: 'Apple MacBook Pro 14" M3 Pro', description: 'The most powerful MacBook Pro ever. M3 Pro chip delivers breakthrough performance for professionals. Up to 22 hours battery, stunning Liquid Retina XDR display.', category: 'Technology', brand: 'Apple', price: 199900, originalPrice: 229900, image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80', rating: 4.9, reviewCount: 2847, keywords: ['laptop', 'apple', 'macbook', 'computer', 'developer', 'macOS', 'professional'], specs: { Chip: 'Apple M3 Pro', RAM: '18GB', Storage: '512GB SSD', Display: '14.2" Liquid Retina XDR', Battery: '22 hrs', Weight: '1.61 kg' }, inStock: true, isFeatured: true, viewCount: 8420, wishlistCount: 1240, compareCount: 890 },
  { name: 'Samsung Galaxy S24 Ultra', description: 'The ultimate Galaxy experience. 200MP camera system, built-in S Pen, titanium frame, Snapdragon 8 Gen 3 for Galaxy. AI-powered features redefine mobile photography.', category: 'Technology', brand: 'Samsung', price: 134999, originalPrice: 149999, image: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&q=80', rating: 4.8, reviewCount: 1923, keywords: ['smartphone', 'samsung', 'android', '5G', 'camera', 'S Pen', 'galaxy'], specs: { Processor: 'Snapdragon 8 Gen 3', RAM: '12GB', Storage: '256GB', Camera: '200MP Quad', Display: '6.8" QHD+ 120Hz', Battery: '5000mAh' }, inStock: true, isFeatured: true, viewCount: 6100, wishlistCount: 980, compareCount: 760 },
  { name: 'Sony WH-1000XM5 Headphones', description: 'Industry-leading noise cancellation with 8 microphones. Exceptional 30-hour battery, crystal-clear hands-free calling, and multipoint connection for seamless audio.', category: 'Technology', brand: 'Sony', price: 29990, originalPrice: 34990, image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80', rating: 4.9, reviewCount: 5632, keywords: ['headphones', 'sony', 'noise cancelling', 'wireless', 'audio', 'ANC', 'bluetooth'], specs: { 'Battery Life': '30 hrs', Connectivity: 'Bluetooth 5.2', Drivers: '30mm', Weight: '250g', Microphones: '8 mics', 'Noise Canceling': 'Industry Leading' }, inStock: true, isFeatured: true, viewCount: 11200, wishlistCount: 2100, compareCount: 1450 },
  { name: 'Nike Air Max 270 React', description: 'Designed for all-day comfort. The Nike Air Max 270 React combines the tallest Air unit in heel with React foam for an incredibly lightweight, springy feel.', category: 'Sports', brand: 'Nike', price: 12995, originalPrice: 15995, image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80', rating: 4.7, reviewCount: 3841, keywords: ['shoes', 'running', 'nike', 'air max', 'sneakers', 'sports', 'athletic'], specs: { Upper: 'Engineered Mesh', Midsole: 'Air Max + React', Sizes: 'UK 6-13', Gender: 'Unisex', 'Heel Height': '38mm Air unit' }, inStock: true, viewCount: 5200, wishlistCount: 890, compareCount: 420 },
  { name: 'Adidas Ultraboost 23 Running', description: 'Energy-returning Boost cushioning propels every stride. PRIMEKNIT+ upper wraps your foot for a sock-like fit. Continental rubber outsole for grip in any condition.', category: 'Sports', brand: 'Adidas', price: 14999, originalPrice: 18999, image: 'https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=800&q=80', rating: 4.8, reviewCount: 2917, keywords: ['adidas', 'ultraboost', 'running', 'boost', 'marathon', 'jogging', 'shoes'], specs: { Upper: 'PRIMEKNIT+', Midsole: 'Boost', Outsole: 'Continental Rubber', Drop: '10mm', Weight: '312g' }, inStock: true, viewCount: 4300, wishlistCount: 720, compareCount: 380 },
  { name: 'Zara Premium Oversized Blazer', description: 'Contemporary oversized silhouette in premium fabric. Notched lapels, welt chest pocket, and flap pockets. Versatile piece that transitions from boardroom to evening.', category: 'Fashion', brand: 'Zara', price: 5999, originalPrice: 8999, image: 'https://images.unsplash.com/photo-1594938298603-c8148c4b4057?w=800&q=80', rating: 4.5, reviewCount: 1284, keywords: ['blazer', 'zara', 'fashion', 'formal', 'jacket', 'office', 'premium'], specs: { Material: '68% Polyester, 32% Viscose', Fit: 'Oversized', Closure: 'Single Button', Sizes: 'XS to XXL', Care: 'Dry Clean' }, inStock: true, viewCount: 2800, wishlistCount: 560, compareCount: 180 },
  { name: 'Tesla Model 3 Long Range AWD', description: 'The benchmark for electric performance. 602km range, 0-100 in 4.4 seconds. Full self-driving capability, 15.4" touchscreen, over-the-air updates, and zero emissions.', category: 'Automotive', brand: 'Tesla', price: 4299000, image: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80', rating: 4.9, reviewCount: 7823, keywords: ['tesla', 'electric', 'EV', 'sedan', 'autopilot', 'sustainable', 'model 3'], specs: { Range: '602 km', '0-100 kmph': '4.4s', Motors: 'Dual (AWD)', Autopilot: 'Full Self-Driving', Screen: '15.4" Touchscreen', Charging: 'Supercharger V3' }, inStock: false, isFeatured: true, viewCount: 15600, wishlistCount: 3200, compareCount: 2100 },
  { name: 'Coursera Data Science Professional', description: 'Complete Data Science specialization by Google. 7 courses covering Python, ML, data visualization, and AI. Earn Google certification. 100% online, self-paced.', category: 'Education', brand: 'Coursera × Google', price: 3999, originalPrice: 5999, image: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800&q=80', rating: 4.8, reviewCount: 14231, keywords: ['education', 'data science', 'python', 'machine learning', 'google', 'certificate', 'AI'], specs: { Courses: '7 courses', Duration: '6 months', Level: 'Beginner friendly', Certificate: 'Google Certificate', Access: 'Lifetime', Language: 'English + subtitles' }, inStock: true, isFeatured: true, viewCount: 9800, wishlistCount: 2400, compareCount: 1100 },
  { name: 'Dyson V15 Detect Absolute', description: 'Laser illuminates dust invisible to the naked eye. Piezo sensor automatically counts and sizes particles, displaying real-time data. 60 minutes of powerful fade-free suction.', category: 'Health', brand: 'Dyson', price: 64900, originalPrice: 69900, image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80', rating: 4.7, reviewCount: 2156, keywords: ['dyson', 'vacuum', 'cordless', 'laser', 'cleaning', 'HEPA', 'home'], specs: { Suction: '230 AW', Battery: '60 mins', Dustbin: '0.77L', Filter: 'HEPA H13', Weight: '3.1kg', Attachments: '10 tools' }, inStock: true, viewCount: 3900, wishlistCount: 680, compareCount: 290 },
  { name: 'Spotify Premium Family Plan', description: 'Music without limits for the whole family. 6 accounts, ad-free music, offline listening, high-quality audio up to 320kbps. Access to 100M+ songs and 5M+ podcasts.', category: 'Entertainment', brand: 'Spotify', price: 179, image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80', rating: 4.6, reviewCount: 89231, keywords: ['spotify', 'music', 'streaming', 'podcast', 'entertainment', 'audio', 'family'], specs: { Accounts: '6 premium accounts', Audio: 'Up to 320kbps', Downloads: 'Offline listening', 'Ad-free': 'Yes', Content: '100M+ songs', Billing: 'Monthly subscription' }, inStock: true, viewCount: 12000, wishlistCount: 4100, compareCount: 890 },
  { name: 'Airbnb Maldives Overwater Villa', description: 'Your own private overwater bungalow with direct ocean access, glass floor panels, and panoramic views. Includes breakfast, snorkeling equipment, and sunset dolphin cruise.', category: 'Travel', brand: 'Airbnb', price: 125000, image: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80', rating: 4.9, reviewCount: 428, keywords: ['maldives', 'travel', 'luxury', 'villa', 'ocean', 'vacation', 'resort'], specs: { Location: 'Maldives', Bedrooms: '1 King Suite', Pool: 'Private Infinity', Duration: '3 nights min', Includes: 'Breakfast + Activities', Access: 'Private boat transfer' }, inStock: true, viewCount: 5600, wishlistCount: 1800, compareCount: 340 },
  { name: 'Whey Protein Gold Standard', description: 'Optimum Nutrition Gold Standard 100% Whey. 24g of blended protein, 5.5g BCAAs, 11g EAAs per serving. Instantized for easy mixing. 74 servings per bag.', category: 'Health', brand: 'Optimum Nutrition', price: 4999, originalPrice: 6499, image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800&q=80', rating: 4.8, reviewCount: 28491, keywords: ['protein', 'whey', 'fitness', 'gym', 'health', 'nutrition', 'workout'], specs: { Protein: '24g per serving', BCAAs: '5.5g', Servings: '74', Calories: '120 kcal', Flavours: '20+ options', Certification: 'Informed Sport' }, inStock: true, isFeatured: true, viewCount: 18200, wishlistCount: 5600, compareCount: 2800 },
];

const ads = [
  { title: 'MacBook Pro M3 — Redefine What a Laptop Can Do', description: 'Experience pro-level performance with Apple M3. Up to 22 hours battery.', category: 'Technology', keywords: ['laptop', 'apple', 'developer', 'professional'], image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80', targetAudience: ['developers', 'designers'], budget: 80000, impressions: 4200, clicks: 378 },
  { title: 'Nike — Push Your Every Limit', description: 'New Air Max collection. Engineered for peak performance and iconic style.', category: 'Sports', keywords: ['nike', 'shoes', 'running', 'fitness'], image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80', targetAudience: ['athletes', 'fitness lovers'], budget: 35000, impressions: 3100, clicks: 217 },
  { title: 'Zara New Season — Style Without Compromise', description: 'Discover the latest collection. Premium fashion for every occasion.', category: 'Fashion', keywords: ['fashion', 'zara', 'style', 'clothing'], image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&q=80', targetAudience: ['fashion enthusiasts'], budget: 28000, impressions: 5800, clicks: 638 },
  { title: 'Tesla — The Future Drives Itself', description: 'Zero emissions, unlimited range. Drive the future today.', category: 'Automotive', keywords: ['tesla', 'electric', 'EV', 'sustainable'], image: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80', targetAudience: ['tech-forward buyers'], budget: 150000, impressions: 7200, clicks: 576 },
  { title: 'Coursera × Google — Your Career Starts Now', description: 'Get Google certified in Data Science. 100% online, job-ready skills.', category: 'Education', keywords: ['education', 'google', 'certificate', 'career'], image: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800&q=80', targetAudience: ['students', 'professionals'], budget: 22000, impressions: 3800, clicks: 418 },
  { title: 'Sony XM5 — Silence Everything Else', description: 'Industry-leading noise cancellation. Hear only what matters to you.', category: 'Technology', keywords: ['headphones', 'sony', 'audio', 'wireless'], image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80', targetAudience: ['music lovers', 'commuters'], budget: 40000, impressions: 4600, clicks: 414 },
  { title: 'Maldives Escape — Paradise Is Calling', description: 'Overwater villas with infinite ocean views. Limited availability.', category: 'Travel', keywords: ['maldives', 'luxury', 'travel', 'vacation'], image: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&q=80', targetAudience: ['luxury travelers'], budget: 60000, impressions: 2900, clicks: 232 },
  { title: 'Gold Standard Whey — Fuel Your Gains', description: '24g protein per serving. The world\'s #1 selling whey protein brand.', category: 'Health', keywords: ['protein', 'fitness', 'gym', 'nutrition'], image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800&q=80', targetAudience: ['gym goers', 'athletes'], budget: 18000, impressions: 6100, clicks: 671 },
];

const seedDatabase = async () => {
  try {
    await connectDB();
    await Promise.all([User.deleteMany({}), Product.deleteMany({}), Ad.deleteMany({})]);
    const [insertedProducts, insertedAds] = await Promise.all([Product.insertMany(products), Ad.insertMany(ads)]);
    console.log(`✅ ${insertedProducts.length} products inserted`);
    console.log(`✅ ${insertedAds.length} ads inserted`);
    const salt = await bcrypt.genSalt(12);
    const hashed = await bcrypt.hash('Admin@123456', salt);
    await User.create({ username: 'admin', email: 'admin@minhand.com', password: hashed, role: 'admin' });
    console.log('✅ Admin created: admin@minhand.com / Admin@123456');
    console.log('\n🎉 MinHand database seeded successfully!');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed error:', err.message);
    process.exit(1);
  }
};

seedDatabase();
